version: "3.8"

services:
  rtmp:
    build: .
    ports:
      - "1935:1935"    # RTMP
      - "8080:8080"    # HTTP
    volumes:
      - ./media:/app/media
    environment:
      - NODE_ENV=development
    restart: unless-stopped