version: "3.8"

services:
  media-server:
    build: .
    ports:
      - "1935:1935"   # RTMP ingest
      - "8080:8080"   # HLS playback
    volumes:
      - ./media:/app/media   # keeps HLS segments/playlist on host
    restart: unless-stopped