# fly.toml app configuration file generated for rtmp-relay on 2025-05-30T09:12:16Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rtmp-server"
primary_region = 'arn'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true 
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

[[services]]
  internal_port = 1935
  protocol = "tcp"

  [[services.ports]]
    port = "1935"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "rtmp_data"
  destination = "/app/media"
